### PR TITLE
Styling challenge

### PR DESCRIPTION
**Pull request by telmaantunes**

### CODE REVIEW

**Comment by telmaantunes** [comment]
Sorry about this, I wanted to create a PR on my fork! 
I tried to fix this by resetting the code here so that it doesn't stay visible but I don't have the permissions to push.

**Comment by pdfrod** [comment]
Don't worry @telmaantunes, we'll ask GitHub support to delete this pull request.

**Comment by pdfrod** [comment]
GitHub's support wasn't of much help unfortunately. Do you see any button here to re-open the branch @telmaantunes? Since we can't delete it, I was thinking about force pushing an empty commit.

**Comment by pdfrod** [comment]
I can't do much I'm afraid, because the branch was never in our repo. Anyway, don't worry about it; let's just let it go.

Be sure to share your solution with `reedsyapplications`, if you haven't done so already.

**Pull request closed without merging**
