### PR TITLE
Create Data Analyst challenge

### PR DESCRIPTION
**Pull request by pdfrod**

### CODE REVIEW

**Comment by pdfrod** [comment]
> Do you think we should orient a bit more the question 4 with a tool we are using? Or it's better to keep it open, and they can use any tool?

It crossed my mind that we could ask them to use Data Studio, but I'm not sure if it's easy / free to setup a Data Studio account these days.

**Comment by madwork** [comment]
> It crossed my mind that we could ask them to use Data Studio, but I'm not sure if it's easy / free to setup a Data Studio account these days.

Yes Data Studio is probably not easy to setup, but I'm wondering about metabase?

**Comment by pdfrod** [comment]
> > It crossed my mind that we could ask them to use Data Studio, but I'm not sure if it's easy / free to setup a Data Studio account these days.
> 
> Yes Data Studio is probably not easy to setup, but I'm wondering about metabase?

Yeah, Metabase would be cool, but I'm not sure how would they send their work to us. Should we have like a sandbox Metabase environment for them to use on the assignment?

**Review by ruimiguelsantos — APPROVED** [review]
Looks great! 👏 I think we could find a way to get their work using metabase, but in my opinion the challenge is fine for now, and we could use it in its current form 👍

**Pull request merged**
